#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url = jdbc:mysql://localhost:3306/Company
#spring.datasource.username = root
#spring.datasource.password = root
#
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect


server.port = 8080

spring.datasource.url = jdbc:postgresql://ec2-52-207-90-231.compute-1.amazonaws.com:5432/dbir0ghmpvcaot
spring.datasource.username = sbgyxeeqoakbvv
spring.datasource.password = 4a6116e31581fe0b75b15f5690179cd2f0a0e7bf37e771c3947dea1ec5a92265

spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
